-- Script to insert 50 dummy residents for tenant 'demo'
-- This avoids setting "full_name" directly because it is a generated column.

INSERT INTO residents (tenant_id, first_name, middle_name, last_name, gender, civil_status, age, residential_address, is_deceased)
VALUES
('demo', 'Juan', 'A.', 'Dela Cruz', 'Male', 'Single', 25, '124 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Maria', 'B.', 'Santos', 'Female', 'Married', 38, '883 Purok 3, Brgy. Demo, Demo City', false),
('demo', 'Jose', 'C.', 'Reyes', 'Male', 'Widowed', 65, '910 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Pedro', 'D.', 'Cruz', 'Male', 'Married', 45, '119 Purok 4, Brgy. Demo, Demo City', false),
('demo', 'Ana', 'E.', 'Bautista', 'Female', 'Single', 22, '334 Purok 5, Brgy. Demo, Demo City', false),
('demo', 'Luis', 'F.', 'Ocampo', 'Male', 'Separated', 52, '543 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Carlos', 'G.', 'Aquino', 'Male', 'Married', 39, '888 Purok 6, Brgy. Demo, Demo City', false),
('demo', 'Elena', 'H.', 'Garcia', 'Female', 'Divorced', 48, '102 Purok 7, Brgy. Demo, Demo City', false),
('demo', 'Rosa', 'I.', 'Mendoza', 'Female', 'Married', 55, '991 Purok 3, Brgy. Demo, Demo City', false),
('demo', 'Miguel', 'J.', 'Gonzales', 'Male', 'Single', 28, '456 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Sofia', 'K.', 'Villanueva', 'Female', 'Widowed', 70, '312 Purok 4, Brgy. Demo, Demo City', false),
('demo', 'David', 'L.', 'Perez', 'Male', 'Married', 41, '610 Purok 5, Brgy. Demo, Demo City', false),
('demo', 'Carmen', 'M.', 'Flores', 'Female', 'Single', 19, '884 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Jorge', 'N.', 'Ramos', 'Male', 'Married', 60, '120 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Lucia', 'A.', 'Castillo', 'Female', 'Separated', 35, '551 Purok 6, Brgy. Demo, Demo City', false),
('demo', 'Daniel', 'B.', 'Rivera', 'Male', 'Single', 24, '318 Purok 7, Brgy. Demo, Demo City', false),
('demo', 'Marcos', 'C.', 'Fernandez', 'Male', 'Married', 51, '672 Purok 3, Brgy. Demo, Demo City', false),
('demo', 'Rafael', 'D.', 'Torres', 'Male', 'Divorced', 43, '903 Purok 5, Brgy. Demo, Demo City', false),
('demo', 'Laura', 'E.', 'Diaz', 'Female', 'Married', 31, '118 Purok 4, Brgy. Demo, Demo City', false),
('demo', 'Teresa', 'F.', 'Gomez', 'Female', 'Widowed', 68, '452 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Juan', 'G.', 'Bautista', 'Male', 'Married', 55, '732 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Elena', 'H.', 'Reyes', 'Female', 'Single', 29, '501 Purok 3, Brgy. Demo, Demo City', false),
('demo', 'Rosa', 'I.', 'Garcia', 'Female', 'Separated', 47, '804 Purok 6, Brgy. Demo, Demo City', false),
('demo', 'Jose', 'J.', 'Mendoza', 'Male', 'Married', 63, '919 Purok 4, Brgy. Demo, Demo City', false),
('demo', 'Sofia', 'K.', 'Torres', 'Female', 'Married', 34, '235 Purok 7, Brgy. Demo, Demo City', false),
('demo', 'David', 'L.', 'Flores', 'Male', 'Single', 27, '441 Purok 5, Brgy. Demo, Demo City', false),
('demo', 'Luis', 'M.', 'Castillo', 'Male', 'Widowed', 72, '189 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Carmen', 'N.', 'Aquino', 'Female', 'Married', 45, '624 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Pedro', 'A.', 'Perez', 'Male', 'Divorced', 50, '821 Purok 3, Brgy. Demo, Demo City', false),
('demo', 'Ana', 'B.', 'Rivera', 'Female', 'Single', 21, '305 Purok 6, Brgy. Demo, Demo City', false),
('demo', 'Carlos', 'C.', 'Gomez', 'Male', 'Married', 37, '555 Purok 4, Brgy. Demo, Demo City', false),
('demo', 'Lucia', 'D.', 'Gonzales', 'Female', 'Separated', 42, '777 Purok 5, Brgy. Demo, Demo City', false),
('demo', 'Miguel', 'E.', 'Ocampo', 'Male', 'Married', 58, '108 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Maria', 'F.', 'Villanueva', 'Female', 'Widowed', 66, '330 Purok 7, Brgy. Demo, Demo City', false),
('demo', 'Rafael', 'G.', 'Cruz', 'Male', 'Single', 26, '491 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Laura', 'H.', 'Santos', 'Female', 'Married', 33, '683 Purok 3, Brgy. Demo, Demo City', false),
('demo', 'Jorge', 'I.', 'Dela Cruz', 'Male', 'Divorced', 49, '915 Purok 6, Brgy. Demo, Demo City', false),
('demo', 'Daniel', 'J.', 'Diaz', 'Male', 'Single', 23, '210 Purok 4, Brgy. Demo, Demo City', false),
('demo', 'Teresa', 'K.', 'Fernandez', 'Female', 'Married', 54, '567 Purok 5, Brgy. Demo, Demo City', false),
('demo', 'Marcos', 'L.', 'Ramos', 'Male', 'Widowed', 61, '832 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Juan', 'M.', 'Ocampo', 'Male', 'Married', 40, '144 Purok 7, Brgy. Demo, Demo City', false),
('demo', 'Elena', 'N.', 'Villanueva', 'Female', 'Separated', 36, '359 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Carlos', 'A.', 'Santos', 'Male', 'Single', 28, '472 Purok 3, Brgy. Demo, Demo City', false),
('demo', 'Rosa', 'B.', 'Dela Cruz', 'Female', 'Married', 59, '698 Purok 6, Brgy. Demo, Demo City', false),
('demo', 'Jose', 'C.', 'Garcia', 'Male', 'Divorced', 52, '904 Purok 4, Brgy. Demo, Demo City', false),
('demo', 'Ana', 'D.', 'Mendoza', 'Female', 'Single', 20, '225 Purok 5, Brgy. Demo, Demo City', false),
('demo', 'David', 'E.', 'Torres', 'Male', 'Married', 44, '513 Purok 1, Brgy. Demo, Demo City', false),
('demo', 'Carmen', 'F.', 'Reyes', 'Female', 'Widowed', 69, '760 Purok 7, Brgy. Demo, Demo City', false),
('demo', 'Miguel', 'G.', 'Bautista', 'Male', 'Separated', 46, '881 Purok 2, Brgy. Demo, Demo City', false),
('demo', 'Lucia', 'H.', 'Flores', 'Female', 'Married', 32, '133 Purok 3, Brgy. Demo, Demo City', false);
